# Unit 23. 2차원 리스트

In [ ]:
# 리스트 [행(row)][열(column)]

In [1]:
a = [[10, 20], [30, 40], [50, 60]]

In [2]:
a

[[10, 20], [30, 40], [50, 60]]

In [3]:
a[1][1]

40

In [5]:
# Numpy array
import numpy as np
arr = np.array(a)
arr

array([[10, 20],
       [30, 40],
       [50, 60]])

In [6]:
arr[1,1]

40

In [7]:
arr[1:,1:]

array([[40],
       [60]])

In [9]:
b = [[10, 20, 15], [30, 40, 35], [50, 60, 55]]

In [10]:
import numpy as np
array = np.array(b)
array

array([[10, 20, 15],
       [30, 40, 35],
       [50, 60, 55]])

In [12]:
array[1:,1:]

array([[40, 35],
       [60, 55]])

In [13]:
# 톱니형 리스트
a = [[1],
    [2, 3],
    [4, 5, 6],
    [7, 8],
    [9]]

In [14]:
a

[[1], [2, 3], [4, 5, 6], [7, 8], [9]]

In [15]:
len(a)

5

In [16]:
for row in a:
    for element in row:
        print(element, end=' ')
    print()

1 
2 3 
4 5 6 
7 8 
9 


In [17]:
for i in range(len(a)):
    for k in range(len(a[i])):
        print(a[i][k], end=' ')
    print()
        

1 
2 3 
4 5 6 
7 8 
9 


In [29]:
import random as rd
mat = []
for i in range(3):
    mat.append(row)
    row = []
    for k in range(6):
        row.append(rd.randint(1, 6))
    mat.append(row)

In [31]:
mc = [[rd.randint(1, 6) for k in range(6)] for i in range(3)]
mc

[[5, 2, 1, 6, 1, 5], [1, 1, 3, 6, 6, 5], [5, 1, 5, 5, 5, 6]]

### 2차원 리스트의 복사

In [33]:
a = [[10, 20], [30, 40]]
b = a.copy()
b

[[10, 20], [30, 40]]

In [34]:
b[1][1] = 100 
a # b의 값을 바꿔줬음에도 불구하고 a값이 바뀐다(리스트 안의 리스트 포인팅은 같기 때문에)

[[10, 20], [30, 100]]

In [35]:
import copy
a = [[10, 20], [30, 40]]
b = copy.deepcopy(a)

In [36]:
b[1][1] = 100
a # a값이 바뀌지 않는다. (deepcopy를 이용)

[[10, 20], [30, 40]]